import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/components/Context/Context";
import Providers from "@/components/ModelLogin/Providers";
import ProtectedRoute from "@/components/ProtectedRoute/ProtectedRoute";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Travel",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <Providers>
          <UserProvider>
            <ProtectedRoute>{children}</ProtectedRoute>
          </UserProvider>
        </Providers>
      </body>
    </html>
  );
}
